<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
    <line>
      <![CDATA[Test case started: doLogin]]>
    </line>
    <line>
      <![CDATA[Test case passed: doLogin]]>
    </line>
    <line>
      <![CDATA[Test case started: doSkip]]>
    </line>
    <line>
      <![CDATA[Testcase has been skipped : doSkip]]>
    </line>
    <line>
      <![CDATA[Test case started: doUserReg]]>
    </line>
    <line>
      <![CDATA[Testcase is being failed : doUserReg]]>
    </line>
    <line>
      <![CDATA[<a href="C:\Users\91733\OneDrive\Desktop\new.png" target="blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href="C:\Users\91733\OneDrive\Desktop\new.png" target="blank"><img src="C:\Users\91733\OneDrive\Desktop\new.png" width=200 height=200 /></a>]]>
    </line>
  </reporter-output>
  <suite started-at="2024-10-29T12:18:48 IST" name="Learning TestNG" finished-at="2024-10-29T12:18:49 IST" duration-ms="97">
    <groups>
    </groups>
    <test started-at="2024-10-29T12:18:48 IST" name="Extent report Test" finished-at="2024-10-29T12:18:49 IST" duration-ms="97">
      <class name="day22.ExtentReportsDemo2">
        <test-method signature="doLogin()[pri:0, instance:day22.ExtentReportsDemo2@626c44e7]" started-at="2024-10-29T12:18:49 IST" name="doLogin" finished-at="2024-10-29T12:18:49 IST" duration-ms="17" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Test case started: doLogin]]>
            </line>
            <line>
              <![CDATA[Test case passed: doLogin]]>
            </line>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method signature="doSkip()[pri:0, instance:day22.ExtentReportsDemo2@626c44e7]" started-at="2024-10-29T12:18:49 IST" name="doSkip" finished-at="2024-10-29T12:18:49 IST" duration-ms="3" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Intentianally skipping the test]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Intentianally skipping the test
at day22.ExtentReportsDemo2.doSkip(ExtentReportsDemo2.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
            <line>
              <![CDATA[Test case started: doSkip]]>
            </line>
            <line>
              <![CDATA[Testcase has been skipped : doSkip]]>
            </line>
          </reporter-output>
        </test-method> <!-- doSkip -->
        <test-method signature="doUserReg()[pri:0, instance:day22.ExtentReportsDemo2@626c44e7]" started-at="2024-10-29T12:18:49 IST" name="doUserReg" finished-at="2024-10-29T12:18:49 IST" duration-ms="5" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User Reg is failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User Reg is failed
at org.testng.Assert.fail(Assert.java:111)
at day22.ExtentReportsDemo2.doUserReg(ExtentReportsDemo2.java:36)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test case started: doUserReg]]>
            </line>
            <line>
              <![CDATA[Testcase is being failed : doUserReg]]>
            </line>
            <line>
              <![CDATA[<a href="C:\Users\91733\OneDrive\Desktop\new.png" target="blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href="C:\Users\91733\OneDrive\Desktop\new.png" target="blank"><img src="C:\Users\91733\OneDrive\Desktop\new.png" width=200 height=200 /></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- doUserReg -->
      </class> <!-- day22.ExtentReportsDemo2 -->
    </test> <!-- Extent report Test -->
  </suite> <!-- Learning TestNG -->
</testng-results>
